import fs from "node:fs";
import path from "node:path";
import assert from "node:assert/strict";
import { visit } from "jsonc-parser";
const root = path.resolve(import.meta.dirname, "../src/i18n");
const registry = JSON.parse(fs.readFileSync(path.resolve(root, "../../../../crates/dtt-i18n/locales.json"), "utf8"));
const catalogs = {};
function leaves(object, prefix = "", result = {}) {
  for (const [key, value] of Object.entries(object)) {
    const name = prefix ? `${prefix}.${key}` : key;
    if (typeof value === "string") { assert(value.trim(), `Empty message: ${name}`); result[name] = value; }
    else { assert(value && !Array.isArray(value), `Invalid message: ${name}`); leaves(value, name, result); }
  }
  return result;
}
function parse(file) {
  const source = fs.readFileSync(file, "utf8");
  const objects = [];
  visit(source, {
    onObjectBegin() { objects.push(new Set()); },
    onObjectProperty(name) {
      const keys = objects.at(-1);
      assert(!keys.has(name), `Duplicate key ${name}: ${file}`);
      keys.add(name);
    },
    onObjectEnd() { objects.pop(); },
    onError(code) { throw new Error(`Invalid JSON ${file}: ${code}`); },
  });
  return JSON.parse(source);
}
const params = value => [...value.matchAll(/{{\s*([\w]+)(?:,[^}]*)?\s*}}/g)].map(m => m[1]).sort();
for (const locale of Object.keys(registry)) {
  catalogs[locale] = Object.fromEntries(fs.readdirSync(`${root}/locales/${locale}`).filter(f => f.endsWith(".json")).sort().map(file => [path.basename(file, ".json"), parse(`${root}/locales/${locale}/${file}`)]));
}
function logical(catalog, locale) {
  const result = {};
  for (const [key, value] of Object.entries(leaves(catalog))) {
    const base = key.replace(/_(zero|one|two|few|many|other)$/, "");
    if (base !== key) {
      for (const category of new Intl.PluralRules(locale).resolvedOptions().pluralCategories) {
        assert(Object.hasOwn(leaves(catalog), `${base}_${category}`), `${locale}: missing plural ${base}_${category}`);
      }
    }
    const arguments_ = params(value);
    if (result[base]) assert.deepEqual(arguments_, result[base], `${locale}: plural parameters differ for ${base}`);
    result[base] = arguments_;
  }
  return result;
}
const baseline = logical(catalogs.en, "en");
for (const [locale, catalog] of Object.entries(catalogs)) assert.deepEqual(logical(catalog, locale), baseline, `${locale}: message or parameter mismatch`);
const generated = "// Generated by scripts/check-i18n.mjs. Do not edit.\nexport type EnglishResources = " + JSON.stringify(catalogs.en, null, 2) + ";\n";
const target = `${root}/resource-types.generated.ts`;
if (process.argv.includes("--write")) fs.writeFileSync(target, generated);
else assert.equal(fs.readFileSync(target, "utf8").replace(/\r\n/g, "\n"), generated, "Resource types are stale; run pnpm i18n:generate");
console.log(`Validated ${Object.keys(baseline).length} messages across ${Object.keys(catalogs).length} locales.`);

const sourceRoot = path.resolve(root, "..");
function sources(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
    const file = path.join(directory, entry.name);
    return entry.isDirectory() ? sources(file) : /\.tsx?$/.test(file) && !/\.test\.|generated\.ts$/.test(file) ? [file] : [];
  });
}
const references = new Set();
for (const file of sources(sourceRoot)) {
  const source = fs.readFileSync(file, "utf8");
  for (const match of source.matchAll(/\$\s*=>\s*\$\.([\w.]+)/g)) references.add(match[1]);
  assert(!/\bt\(\s*["'`]/.test(source), `Use typed translation selectors: ${file}`);
  assert(!/\p{Script=Han}/u.test(source), `Move user-facing text into catalogs: ${file}`);
  assert(!/\b(?:aria-label|placeholder|title)="[A-Za-z][^"]*"/.test(source), `Translate JSX labels: ${file}`);
}
for (const key of Object.keys(baseline)) {
  const leaf = key.slice(key.indexOf(".") + 1);
  assert([...references].some(ref => leaf === ref || leaf.startsWith(`${ref}.`)), `Unused message: ${key}`);
}
