[package]
name = "dtt-i18n"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
fluent-bundle.workspace = true
icu_locale_core.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json = "1"

[build-dependencies]
fluent-bundle.workspace = true
fluent-syntax = "0.12"
