[package]
name = "dtt-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Command line interface for Stellaris Dynamic Technology Tree generation"

[[bin]]
name = "dtt"
path = "src/main.rs"

[dependencies]
sys-locale.workspace = true
dtt-i18n.workspace = true
anyhow.workspace = true
clap.workspace = true
dtt-application.workspace = true
