// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";
import type { ErrorContextDto } from "./ErrorContextDto";

export type AppError = { code: ErrorCode, technicalDetail?: string, context?: ErrorContextDto, };
