// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { DetectedEnvironmentDto } from "./DetectedEnvironmentDto";

export type BootstrapDataDto = { environment: DetectedEnvironmentDto, environmentError?: AppError, outputDirectory: string, };
