// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextReasonDto = "missing_previous_scope" | "missing_event_source" | "missing_founder_species" | "unknown_species_relation" | "unknown_owner" | "unknown_trigger" | "expected_scalar" | "unbound_argument" | "invalid_boolean" | "missing_identity" | "unverified_structure" | "unknown_scope" | "unknown_collection" | "recursive_script" | "type_mismatch";
