export type ErrorCode =
  | "INVALID_ENVIRONMENT"
  | "SAVE_UNAVAILABLE"
  | "SAVE_CONTAINER_CORRUPT"
  | "UNSUPPORTED_BINARY_SAVE"
  | "PLAYER_COUNTRY_MISSING"
  | "PLAYER_COUNTRY_REQUIRED"
  | "LAUNCHER_DATABASE_UNAVAILABLE"
  | "GENERATION_BUSY"
  | "GENERATION_CANCELLED"
  | "INTERNAL";
