// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenerationStageDto = "SAVE_PARSE" | "LOAD_ORDER" | "INGEST_TECH" | "RELATIONS" | "INGEST_L10N" | "RENDER" | "CYCLES" | "WRITE_OUTPUT" | "DONE";
