// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DefinitionIssueDto } from "./DefinitionIssueDto";
import type { LocalisationFailureKindDto } from "./LocalisationFailureKindDto";
import type { UnknownConditionDto } from "./UnknownConditionDto";
import type { WriteOperationDto } from "./WriteOperationDto";

export type GenerationDiagnosticItemDto = { "kind": "missing_mod_descriptor", modName: string, } | { "kind": "unknown_condition", reason: UnknownConditionDto, name: string, occurrences: number, technologies: Array<string>, } | { "kind": "deferred_condition", name: string, occurrences: number, technologies: Array<string>, } | { "kind": "game_data", source: string, category: string, diagnosticKind: string, subject: string | null, byteOffset: number | null, issue: DefinitionIssueDto, technicalDetail: string | null, } | { "kind": "unhandled_definition", technology: string, source: string, fields: Array<string>, } | { "kind": "localisation", reason: LocalisationFailureKindDto, language: string, source: string, path: string, technicalDetail: string, } | { "kind": "self_reference", technology: string, } | { "kind": "cycle", technologies: Array<string>, } | { "kind": "write_failed", path: string, operation: WriteOperationDto, technicalDetail: string, };
