// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationStageDto } from "./GenerationStageDto";

export type GenerationProgressDto = { "type": "stage_changed", stage: GenerationStageDto, percent: number, };
