// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationDiagnosticItemDto } from "./GenerationDiagnosticItemDto";

export type GenerationDiagnosticsDto = { loadOrder: Array<GenerationDiagnosticItemDto>, unknownConditions: Array<GenerationDiagnosticItemDto>, deferredConditions: Array<GenerationDiagnosticItemDto>, gameData: Array<GenerationDiagnosticItemDto>, unhandledDefinitions: Array<GenerationDiagnosticItemDto>, localisation: Array<GenerationDiagnosticItemDto>, cycles: Array<GenerationDiagnosticItemDto>, writeFailures: Array<GenerationDiagnosticItemDto>, };
