// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppLocaleDto } from "./AppLocaleDto";
import type { GenerationSettingsDto } from "./GenerationSettingsDto";

export type GenerationRequestDto = { saveFile: string, reportLocale: AppLocaleDto, countryId?: number, settings: GenerationSettingsDto, };
