// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationDiagnosticItemDto } from "./GenerationDiagnosticItemDto";
import type { GenerationDiagnosticsDto } from "./GenerationDiagnosticsDto";
import type { GenerationStatusDto } from "./GenerationStatusDto";

export type GenerationResultDto = { status: GenerationStatusDto, sourceCount: number, technologyCount: number, eligibleCount: number, swapMatched: number, swapNoMatch: number, swapUncertain: number, written: Array<string>, removed: Array<string>, failed: Array<GenerationDiagnosticItemDto>, reportPath?: string, diagnostics: GenerationDiagnosticsDto, };
