// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameLanguageDto } from "./GameLanguageDto";
import type { SwapUnknownStrategyDto } from "./SwapUnknownStrategyDto";
import type { UnknownStrategyDto } from "./UnknownStrategyDto";

export type GenerationSettingsDto = { stellarisRoot: string, launcherDb: string, languages: Array<GameLanguageDto>, unknownStrategy: UnknownStrategyDto, swapUnknownStrategy: SwapUnknownStrategyDto, };
