// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerCountryCandidateDto } from "./PlayerCountryCandidateDto";
import type { SnapshotDto } from "./SnapshotDto";

export type InspectedSaveDto = { snapshot?: SnapshotDto, playerCountries: Array<PlayerCountryCandidateDto>, };
