// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveScanFailureKindDto } from "./SaveScanFailureKindDto";

export type SaveScanDiagnosticDto = { path: string, kind: SaveScanFailureKindDto, technicalDetail: string, };
