// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveScanFailureKindDto = "steam_users" | "steam_user_entry" | "save_root" | "campaign_entry" | "campaign" | "save_entry" | "file_metadata";
