// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveIndexDto } from "./SaveIndexDto";

export type SaveCampaignDto = { key: string, saves: Array<SaveIndexDto>, };
