// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveAccountDto } from "./SaveAccountDto";
import type { SaveScanDiagnosticDto } from "./SaveScanDiagnosticDto";

export type SaveLibraryDto = { diagnostics: Array<SaveScanDiagnosticDto>, accounts: Array<SaveAccountDto>, };
