// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveIndexStateDto } from "./SaveIndexStateDto";
import type { SaveMetadataDto } from "./SaveMetadataDto";
import type { SaveUnavailableReasonDto } from "./SaveUnavailableReasonDto";

export type SaveIndexDto = { path: string, fileName: string, metadata?: SaveMetadataDto, modifiedAtMillis: number, fileSize: number, state: SaveIndexStateDto, unavailableReason?: SaveUnavailableReasonDto, };
