// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveCampaignDto } from "./SaveCampaignDto";

export type SaveAccountDto = { campaigns: Array<SaveCampaignDto>, };
