// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveLibrarySourceDto } from "./SaveLibrarySourceDto";

export type ScanSaveLibraryRequestDto = { source: SaveLibrarySourceDto, documentsDir?: string, steamLibraries: Array<string>, };
