// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GovernmentDto } from "./GovernmentDto";
import type { SpeciesDto } from "./SpeciesDto";

export type SnapshotDto = { ethics: Array<string>, government: GovernmentDto, ascensionPerks: Array<string>, traditions: Array<string>, founderSpecies: SpeciesDto, countryType: string, };
