// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextReasonDto } from "./ContextReasonDto";

export type UnknownConditionDto = { "kind": "trigger" } | { "kind": "operator", operator: string, } | { "kind": "malformed_argument" } | { "kind": "structured_argument", keys: Array<string>, } | { "kind": "context", reason: ContextReasonDto, scopePath: Array<string>, calls: Array<string>, expected: string | null, actual: string | null, };
