// Generated by scripts/check-i18n.mjs. Do not edit.
export type EnglishResources = {
  "common": {
    "steps": {
      "settings": "Environment & Settings",
      "saves": "Save & Empire",
      "generate": "Generate",
      "results": "Results & Diagnostics"
    },
    "actions": {
      "nextToSaves": "Next: Select Save",
      "prevToSettings": "Back: Environment & Settings",
      "startGeneration": "Start Generation",
      "cancel": "Cancel",
      "cancelling": "Cancelling...",
      "openOutputDirectory": "Open Output Directory",
      "changeSave": "Change Save",
      "modifySettings": "Modify Settings",
      "modify": "Modify",
      "restore": "Reset",
      "reset": "Reset to Detected",
      "refresh": "Rescan",
      "rescanEnvironment": "Rescan Environment",
      "close": "Close",
      "retry": "Retry"
    },
    "settings": {
      "title": "Settings",
      "theme": "Theme",
      "themeLight": "Light",
      "themeDark": "Dark",
      "themeSystem": "System",
      "about": "About DTT",
      "version": "Version",
      "license": "License",
      "aboutText": "Dynamic Technology Tree is a desktop tool for computing and exporting technology dependency trees and localisation from Stellaris saves and active mods.",
      "localeSaveFailed": "Preferences could not be saved. Current choices remain active for this session.",
      "localePreference": "Interface Language"
    },
    "wizard": {
      "ariaLabel": "Wizard steps"
    },
    "hints": {
      "needEnvironment": "Configure and detect the Stellaris install and documents directories first",
      "settingsAutosaved": "Environment and settings changes are saved automatically",
      "saveSelected": "Selected: {{name}}",
      "selectSave": "Select a save",
      "generationReady": "Generation complete. You can load the mod in-game."
    },
    "status": {
      "ready": "Ready",
      "incomplete": "Incomplete"
    },
    "appTitle": "DTT — Dynamic Technology Tree",
    "feedback": "Feedback: QQ group {{group}}",
    "noDate": "No date"
  },
  "diagnostics": {
    "missing_mod_descriptor": "Missing descriptor.mod: {{name}}. The MOD is loaded without its replace_path rules.",
    "game_data": "Game data diagnostic: {{source}} / {{subject}} / {{category}} / {{reason}} / {{offset}}",
    "unhandled_definition": "Unhandled fields in {{technology}} ({{source}}): {{items}}",
    "localisation": "Localisation read failed: {{language}} / {{source}} / {{path}} / {{reason}}",
    "self_reference": "Self reference: {{technology}}",
    "cycle": "Dependency cycle: {{items}}",
    "write_failed": "Failed to {{operation}}: {{path}}",
    "operations": {
      "write": "write",
      "remove": "remove",
      "format": "format"
    },
    "unknown_condition_other": "Unknown condition {{name}}: {{count, number}} occurrences; technologies: {{items}}",
    "unknown_condition_one": "Unknown condition {{name}}: {{count, number}} occurrence; technology: {{items}}",
    "deferred_condition_other": "Deferred condition {{name}}: {{count, number}} occurrences; technologies: {{items}}",
    "deferred_condition_one": "Deferred condition {{name}}: {{count, number}} occurrence; technology: {{items}}",
    "issues": {
      "invalid_utf8": "File is not valid UTF-8.",
      "invalid_syntax": "Invalid Clausewitz syntax.",
      "expected_scalar": "Expected a scalar value.",
      "expected_object": "Expected an object.",
      "invalid_field": "Missing or invalid field: {{field}}.",
      "overwritten": "Definition overwritten by the current source. Previous source: {{previous}}.",
      "inline_cycle": "Inline script contains a cycle: {{script}}.",
      "inline_missing": "Inline script not found: {{script}}.",
      "invalid_inline_call": "inline_script must be a path or an object with a script field.",
      "isolated_branch": "Isolated else_if or else cannot be converted reliably.",
      "invalid_condition": "Condition structure cannot be converted.",
      "malformed_argument": "Trigger arguments cannot be parsed.",
      "structured_argument": "Nested trigger arguments have no supported interpreter.",
      "duplicate_parameter": "Duplicate parameters prevent reliable evaluation.",
      "invalid_swap": "Skipping swap {{index}}: missing or invalid {{field}}.",
      "duplicate_field": "Duplicate field {{field}}; only the first is read. Game merge rules are unverified.",
      "field_case": "Field {{field}} differs in case from {{expected}}; no automatic conversion is applied."
    },
    "conditions": {
      "trigger": "Unrecognized trigger",
      "operator": "Unsupported comparison operator",
      "malformed_argument": "Invalid trigger arguments",
      "structured_argument": "Unsupported structured arguments",
      "missing_previous_scope": "No corresponding previous scope",
      "missing_event_source": "Technology conditions have no event source object",
      "missing_founder_species": "Founder species was not extracted",
      "unknown_species_relation": "Species relation is unverified",
      "unknown_owner": "Cannot determine a unique owner country",
      "unknown_trigger": "Unrecognized trigger; uncertainty retained",
      "expected_scalar": "Identity condition requires a scalar",
      "unbound_argument": "Empty argument or unbound variable",
      "invalid_boolean": "Boolean conditions require yes or no",
      "missing_identity": "Opening identity data is missing or unreadable",
      "unverified_structure": "Condition structure is unverified",
      "unknown_scope": "Unresolved scope reference",
      "unknown_collection": "Collection type or source is unknown",
      "recursive_script": "Recursive scripted trigger",
      "type_mismatch": "Target type mismatch"
    },
    "localisationReasons": {
      "invalid_utf8": "File is not valid UTF-8.",
      "read_failed": "File could not be read."
    }
  },
  "empire": {
    "inspecting": "Inspecting save and empire data...",
    "countryLabel": "Country #{{id}}",
    "sections": {
      "civics": "Civics",
      "ethics": "Ethics",
      "traits": "Species Traits",
      "ascensionPerks": "Ascension Perks",
      "traditions": "Traditions"
    },
    "metrics": {
      "authority": "Authority",
      "origin": "Origin",
      "species": "Founder Species",
      "countryType": "Country Type"
    },
    "defaults": {
      "authority": "Unspecified",
      "origin": "Default origin",
      "species": "Standard biological",
      "countryType": "Unknown type"
    },
    "tabs": {
      "civics": "Ethics & Civics",
      "traits": "Species & Traits",
      "ascension": "Ascension & Traditions"
    },
    "empty": {
      "ethics": "No ethics",
      "civics": "No civic data",
      "traits": "No trait data",
      "ascensionPerks": "No ascension perks",
      "traditions": "No tradition data"
    },
    "civicBadge": "Civic",
    "playerCountrySwitch": "Player country",
    "selectSaveHint": "Select a valid non-ironman text save from the list on the left",
    "detail": "Details",
    "showLess": "Show less",
    "showMore_other": "Show {{count, number}} more",
    "showMore_one": "Show {{count, number}} more"
  },
  "environment": {
    "dialog": {
      "selectGameRoot": "Select Stellaris Game Directory",
      "selectDocumentsDir": "Select Stellaris Documents Directory",
      "selectLauncherDb": "Select launcher-v2.sqlite File",
      "sqliteFilter": "SQLite Database"
    },
    "pathsTitle": "Environment Paths",
    "settingsTitle": "Generation Settings",
    "paths": {
      "gameRoot": "1. Stellaris Install Path",
      "documentsDir": "2. Documents Directory (Paradox Interactive)",
      "launcherDb": "3. Launcher Database (launcher-v2.sqlite)",
      "outputDir": "4. Output Directory"
    },
    "placeholders": {
      "gameRoot": "Stellaris install root is not set",
      "documentsDir": "Documents directory is not set",
      "launcherDb": "Launcher database is not set",
      "outputDir": "Application directory"
    },
    "outputDirBadge": "App directory"
  },
  "errors": {
    "codeHints": {
      "LAUNCHER_DATABASE_UNAVAILABLE": "Launcher database (launcher-v2.sqlite) is unreadable or missing. Please browse and select a valid database file.",
      "SAVE_UNAVAILABLE": "Specified save file does not exist or lacks read permission. Please refresh the save library or reselect a save.",
      "SAVE_CONTAINER_CORRUPT": "Save container or internal gamestate structure is corrupt. Please try another save.",
      "UNSUPPORTED_BINARY_SAVE": "Ironman or binary saves cannot be parsed. DTT only supports non-ironman text saves.",
      "PLAYER_COUNTRY_MISSING": "No player-controlled empire was found in this save file. Please confirm if this is a player save.",
      "PLAYER_COUNTRY_REQUIRED": "Multiple player empires found in save. Please select an empire in the Empire card.",
      "GENERATION_BUSY": "A generation task is already running. Please wait or cancel the active task before starting a new one.",
      "GENERATION_CANCELLED": "Generation task was cancelled per user request.",
      "INTERNAL": "An internal error occurred. You can expand the technical details below when reporting this issue.",
      "MISSING_SETTING": "A required environment setting is missing. Select the game directory, documents directory, and launcher database.",
      "INVALID_PATH": "The selected path is unavailable or has the wrong type. Check the environment paths.",
      "NO_OUTPUT_LANGUAGE": "Select at least one game output language.",
      "EXECUTABLE_PATH_UNAVAILABLE": "The executable location could not be determined. Check the application installation.",
      "NO_TECHNOLOGY_DEFINITIONS": "No technologies were loaded from common/technology. Check the game directory and active MODs."
    },
    "remedy": {
      "retry": "Retry"
    },
    "details": "Technical Details",
    "path": "Path: {{path}}",
    "titles": {
      "SAVE_UNAVAILABLE": "Save unavailable",
      "SAVE_CONTAINER_CORRUPT": "Corrupt save",
      "UNSUPPORTED_BINARY_SAVE": "Unsupported binary or ironman save",
      "PLAYER_COUNTRY_MISSING": "No player empire found",
      "PLAYER_COUNTRY_REQUIRED": "Select a player empire",
      "LAUNCHER_DATABASE_UNAVAILABLE": "Launcher database unavailable",
      "GENERATION_BUSY": "Generation already running",
      "GENERATION_CANCELLED": "Generation cancelled",
      "INTERNAL": "Internal error",
      "MISSING_SETTING": "Missing required setting",
      "INVALID_PATH": "Invalid path",
      "NO_OUTPUT_LANGUAGE": "No output language selected",
      "EXECUTABLE_PATH_UNAVAILABLE": "Output directory unavailable",
      "NO_TECHNOLOGY_DEFINITIONS": "No technology definitions"
    }
  },
  "generation": {
    "outputLanguages": {
      "title": "Output Languages",
      "description": "These are the localization languages written into the mod, unrelated to the app's interface language.",
      "hint": "Please select at least one output language",
      "items": {
        "english": "English",
        "simp_chinese": "Simplified Chinese"
      },
      "selectedCount_other": "{{count, number}} languages selected",
      "selectedCount_one": "{{count, number}} language selected"
    },
    "advanced": {
      "unknownStrategy": {
        "title": "Unknown Condition Handling",
        "description": "Determines how technologies with unresolvable trigger conditions are handled",
        "includeFlagged": {
          "label": "Include and Flag (Recommended)"
        },
        "excludeStrict": {
          "label": "Strict Exclusion"
        },
        "error": {
          "label": "Treat as Error"
        }
      },
      "swapUnknownStrategy": {
        "title": "Uncertain Variant Handling",
        "description": "Keep the base display or stop when the initial identity cannot determine a variant",
        "keepBase": {
          "label": "Keep base technology"
        },
        "error": {
          "label": "Treat as Error"
        }
      }
    },
    "failure": {
      "title": "Generation Failed · Error Report",
      "description": "Generation has stopped. Copy the error report to report the issue, or return to save selection.",
      "code": "Error code",
      "message": "Message",
      "path": "Related path",
      "detail": "Details",
      "copy": "Copy report",
      "copied": "Error report copied",
      "copyFailed": "Copy failed. Select the report above to copy it manually, or try again.",
      "return": "Return"
    },
    "running": {
      "title": "Generating Technology Tree",
      "longWaitHint": "Reading tech definitions and localizations. This step may take longer if you have many active mods...",
      "cancelling": "Cancelling generation task..."
    },
    "stages": {
      "SAVE_PARSE": "Parse Save Game",
      "LOAD_ORDER": "Resolve Load Order",
      "INGEST_TECH": "Ingest Tech Definitions",
      "RELATIONS": "Build Dependencies",
      "INGEST_L10N": "Ingest Localisations",
      "RENDER": "Precompute Render",
      "CYCLES": "Detect Cycles",
      "WRITE_OUTPUT": "Write Output Files",
      "DONE": "Done"
    },
    "barriers": {
      "needSave": "Please select a save game",
      "invalidSave": "This save cannot be parsed. Please select a non-ironman save.",
      "needEmpire": "Please select an empire",
      "needLanguage": "Please select at least one output language"
    }
  },
  "results": {
    "title": "Generation Results",
    "banner": {
      "success": {
        "title": "Generation Completed",
        "description": "Successfully exported {{writtenCount, number}} localisation and dependency tree files."
      },
      "incomplete": {
        "title": "Partially Completed",
        "description": "{{failedCount, number}} files failed to write, while {{writtenCount, number}} files were generated normally."
      }
    },
    "stats": {
      "sources": "Data Sources",
      "totalTech": "Total Techs",
      "totalTechDesc": "Combined technology definitions",
      "eligibleTech": "Eligible Techs",
      "eligibleTechDesc": "Future technology routes retained for the selected empire identity",
      "swaps": "Tech Swaps",
      "swapsDesc": "{{matched, number}} matched, {{noMatch, number}} unmatched, {{uncertain, number}} uncertain",
      "sourcesDesc_other": "{{count, number}} total base and mod sources",
      "sourcesDesc_one": "{{count, number}} total base and mod sources"
    },
    "files": {
      "title": "Output Files",
      "written": "Written Files",
      "removed": "Removed Legacy Files",
      "failed": "Failed Files",
      "report": "Diagnostics Report"
    },
    "diagnostics": {
      "title": "Diagnostics",
      "categories": {
        "loadOrder": {
          "title": "Mod Loading Notices",
          "description": "Mods loaded without descriptor files"
        },
        "unknownConditions": {
          "title": "Unknown Conditions",
          "description": "Undetermined triggers and affected technologies"
        },
        "deferredConditions": {
          "title": "Future Conditions",
          "description": "Event, progression, and object conditions retained as future possibilities"
        },
        "gameData": {
          "title": "Game Data Ingestion",
          "description": "Issues encountered while parsing game and mod files"
        },
        "unhandledDefinitions": {
          "title": "Unhandled Fields",
          "description": "Unrecognized fields in technology definitions"
        },
        "localisation": {
          "title": "Localisation",
          "description": "Localisation file parsing and formatting issues"
        },
        "cycles": {
          "title": "Dependency Cycles",
          "description": "Cyclic and self-referencing dependencies between technologies"
        },
        "writeFailures": {
          "title": "Write Failures",
          "description": "Files that could not be written to destination"
        }
      },
      "truncated_other": "There are {{count, number}} more diagnostic items not displayed here. See the report file for full details.",
      "truncated_one": "There are {{count, number}} more diagnostic item not displayed here. See the report file for full details."
    },
    "guide": {
      "title": "How to Enable in Game",
      "step1": "Create a new mod folder in Documents/Paradox Interactive/Stellaris/mod, and create descriptor.mod inside it;",
      "step2": "Copy the entire localisation folder from the output directory into your new mod folder;",
      "step3": "Enable the mod in the Stellaris Launcher playset and drag it to the VERY BOTTOM of the load order.",
      "importantNote": "IMPORTANT: Place this mod at the very bottom of the load order, otherwise texts will be overridden by other mods."
    },
    "empty": "No generation result available",
    "guideLoadOrderTitle": "Load order requirement"
  },
  "saves": {
    "title": "Select Save Game",
    "sources": {
      "local": "Local Saves",
      "steamCloud": "Steam Cloud"
    },
    "manualSelect": "Select Save from File...",
    "libraryTitle": "Save Library",
    "empireTitle": "Empire Inspection",
    "manualSelectFile": "Choose .sav file",
    "listAriaLabel": "Save list",
    "gameDate": "In-game date: {{date}}",
    "binaryWarning": "Ironman/binary saves are not supported. Use a non-ironman text save.",
    "corruptFallback": "The save file is corrupt and cannot be read",
    "customSelection": "Custom selection",
    "state": {
      "text": {
        "badge": "Plain text"
      },
      "binary": {
        "badge": "Ironman"
      },
      "corrupt": {
        "badge": "Corrupt"
      }
    },
    "empty": {
      "local": {
        "title": "No local saves found",
        "description": "Please verify your documents directory or use the button below to pick a save file manually."
      },
      "steamCloud": {
        "title": "No cloud saves found",
        "description": "No Steam cloud saves detected or Steam library list is empty. Please verify Steam Cloud synchronization."
      }
    },
    "availableCount_other": "{{count, number}} available saves",
    "availableCount_one": "{{count, number}} available save",
    "scanFailures": {
      "steam_users": "Cannot read Steam user directory: {{path}}",
      "steam_user_entry": "Cannot read Steam user entry: {{path}}",
      "save_root": "Cannot read save directory: {{path}}",
      "campaign_entry": "Cannot read campaign entry: {{path}}",
      "campaign": "Cannot read campaign directory: {{path}}",
      "save_entry": "Cannot read save entry: {{path}}",
      "file_metadata": "Cannot read save attributes: {{path}}"
    }
  }
};
